spring.application.name=basketball-stats-api

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:basketball_stats}
spring.datasource.username=${DB_USER:basketball_stats}
spring.datasource.password=${DB_PASSWORD:basketball_stats}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

